In [38]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [2]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [28]:
lr = LogisticRegression(max_iter=200)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9666666666666667

In [29]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9916666666666667

In [30]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9861111111111112

In [32]:
kf = KFold(n_splits=3)

for train_index, test_index in kf.split([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [34]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [36]:
folds = StratifiedKFold()

scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    scores_lr.append(get_score(LogisticRegression(max_iter=200), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [37]:
scores_lr, scores_svm, scores_rf

([0.9222222222222223,
  0.8694444444444445,
  0.9415041782729805,
  0.9415041782729805,
  0.8969359331476323],
 [0.9611111111111111,
  0.9444444444444444,
  0.9832869080779945,
  0.9888579387186629,
  0.9387186629526463],
 [0.9277777777777778,
  0.9166666666666666,
  0.9610027855153204,
  0.9637883008356546,
  0.9275766016713092])

In [47]:
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target).mean()

0.914322191272052

In [48]:
cross_val_score(SVC(), digits.data, digits.target).mean()

0.9632838130609718

In [49]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target).mean()

0.9432590529247911